#!/usr/bin/env bash
# shellcheck disable=SC2154
# configures a brand new Ubuntu machinE

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo sed -i "11i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx start