#!/usr/bin/env bash
#  Bash script that configures a new Ubuntu machine to HAproxy
sudo apt-get update
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get update
sudo apt-get -y install haproxy=2.0.\*
echo "frontend load-banlancer
    bind *:80
    mode http
    default_backend web-backend" >> /etc/haproxy/haproxy.cfg
echo "backend web-backend
    balance roundrobin
    server 3123-web-01 35.237.154.2:80 check
    server 3123-web-02 34.73.23.220:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart