#!/usr/bin/env bash
# Nginx user
chmod 777 /etc/nginx/nginx.conf
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-available/default
pkill -9 apache2
su nginx -c "service nginx restart"
