#!/usr/bin/env bash
# Using what you did for task #0, make your fix short and sweet
sudo sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo kill -9 "$(cat /run/nginx.pid)"
