#!/usr/bin/env bash 
# configuring a new ubuntu machine to respect requirements
apt-get -y update
apt-get -y install nginx
sed -i '0,/listen .*/s//listen 80 default_server;/' /etc/nginx/sites-available/default
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
service nginx restart