#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains a string

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
ADD404_NOTFOUND="error_page 404 /custom_404.html;\n\\t location = /custom_404.html {\n\t\t root /usr/share/nginx/html;\n\t\t internal; \n\t}\n"
PATTERN="#error_page 404 /404.html;"

echo 'Holberton School' > /var/www/html/index.nginx-debian.html
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default


echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i "s@$PATTERN@$ADD404_NOTFOUND@" /etc/nginx/sites-available/default #uncomment and replace
sudo nginx -t
sudo service nginx restart
